# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0c8cc20485a3cf2aa28eb349745b4bbb149569356fe5e394bc1499f1faf87e1da40d6fa7ffce1ea55e6ef2f1c3e965ec5f9b9c976f74306407d63257292f474

test:
  secret_key_base: 387bfe26bd691851a496a0d0bb18fd9b3076da9b27ead4afe2718ed5b2e359f61c968d63fc952845a1f817eb716849bae870e1c9a8725b962d952efbb73fed6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
